
# This file is for integration with Travis CI
before install:
    # update
    - sudo apt-get update
    # set gradlew file permissions
    - chmod +x app/gradlew

matrix:
    include:
        - language: node_js
          node_js:
            - 12
#          services: ## removed per issue: mongod starts by default thus unable to bind to default port
#            - mongodb

          install:
            - npm install --dev
            - npm install --dev ./server
            - npm install --dev ./parser
          
          script:
            # node_js build
            # this is a placeholder for test or build script
            - npm test
            
            
        - language: android
          dist: trusty
          android:
                components:
                    - build-tools-29.0.2
                    - android-29
                
                    - extra-google-google_play_services
                    - extra-google-m2repository
                    - extra-android-m2repository
          
          script:
            # android build
            - ./app/gradlew build 
